name: Build Cordova Android APK (Debug)

on:
  push:
    branches:
      - cordova

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0  # fetch full history for checking commits in submodule

    - name: Build APK
      if: steps.check_submodule.outputs.submodule_changed == 'true'
      run: |
        npm install
        npx cordova platform add android 
        npx cordova build android

    - name: Upload APK artifact
      if: steps.check_submodule.outputs.submodule_changed == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk

