name: Build Cordova Android APK (Release)
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Nothing to do
      run: |
        echo "This will fail"
        end of file

